Folder Added:- Assignment2
Pawan1005/MI-12-MEAN pull request #118
Opened 2021-09-16 15:42 UTC by sandeep597

2021-09-19 06:01 UTC, Pawan1005 requested changes

2021-09-19 06:01 UTC, Pawan1005 commented on SandeepJha/Bootstrap/Assignment 3/Question1.html
> +</head>
create proper indentation

2021-09-19 14:18 UTC, sandeep597 commented on SandeepJha/Bootstrap/Assignment 3/Question1.html
> +</head>
Done.

2021-09-21 11:51 UTC, Pawan1005 requested changes

2021-09-21 11:51 UTC, Pawan1005 commented on SandeepJha/Bootstrap/Assignment 4/.vscode/settings.json
> +}
remove this file

2021-09-21 11:51 UTC, Pawan1005 commented on SandeepJha/Bootstrap/Assignment 4/Question1.html
> +</head>
do proper indentation for head part

2021-09-21 11:51 UTC, Pawan1005 commented on SandeepJha/Bootstrap/Assignment 5/Question1.html
> +</head>
do proper indentation for head part

2021-09-22 13:28 UTC, sandeep597 commented on SandeepJha/Bootstrap/Assignment 4/Question1.html
> +</head>
done

2021-09-22 13:29 UTC, sandeep597 commented on SandeepJha/Bootstrap/Assignment 4/.vscode/settings.json
> +}
done

2021-09-25 13:07 UTC, merged