Subham@123
Pawan1005/MI-12-MEAN pull request #126
Opened 2021-09-20 12:09 UTC by SUBHAM-DASH

successfully uploaded file

2021-09-21 11:54 UTC, Pawan1005 requested changes

2021-09-21 11:54 UTC, Pawan1005 commented on subham/BOOTSTRAP/Assignment5/quest1.html
> +</html>
make proper indentation

2021-09-21 11:54 UTC, Pawan1005 commented on subham/BOOTSTRAP/Assignment4/guest1.html
> +</html>
make proper indentation

2021-09-21 11:54 UTC, Pawan1005 commented on subham/BOOTSTRAP/Assignment3/quest3.html
> +</html>
make proper indentation

2021-09-21 15:23 UTC, SUBHAM-DASH commented
okay sir

2021-09-22 08:56 UTC, Pawan1005 approved these changes

2021-09-24 17:46 UTC, merged